/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedLimitedRouteImport } from './routes/_authenticated/limited'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedForestRouteImport } from './routes/_authenticated/forest'
import { Route as AuthenticatedForestShopRouteImport } from './routes/_authenticated/forest.shop'
import { Route as AuthenticatedForestCalendarRouteImport } from './routes/_authenticated/forest.calendar'
import { Route as ApiPublicHooksNativeUsageRouteImport } from './routes/api/public/hooks/native-usage'
import { Route as AuthenticatedForestDayDayRouteImport } from './routes/_authenticated/forest.day.$day'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLimitedRoute = AuthenticatedLimitedRouteImport.update({
  id: '/limited',
  path: '/limited',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForestRoute = AuthenticatedForestRouteImport.update({
  id: '/forest',
  path: '/forest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForestShopRoute = AuthenticatedForestShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedForestRoute,
} as any)
const AuthenticatedForestCalendarRoute =
  AuthenticatedForestCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedForestRoute,
  } as any)
const ApiPublicHooksNativeUsageRoute =
  ApiPublicHooksNativeUsageRouteImport.update({
    id: '/api/public/hooks/native-usage',
    path: '/api/public/hooks/native-usage',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedForestDayDayRoute =
  AuthenticatedForestDayDayRouteImport.update({
    id: '/day/$day',
    path: '/day/$day',
    getParentRoute: () => AuthenticatedForestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/forest': typeof AuthenticatedForestRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/limited': typeof AuthenticatedLimitedRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/forest/calendar': typeof AuthenticatedForestCalendarRoute
  '/forest/shop': typeof AuthenticatedForestShopRoute
  '/forest/day/$day': typeof AuthenticatedForestDayDayRoute
  '/api/public/hooks/native-usage': typeof ApiPublicHooksNativeUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/forest': typeof AuthenticatedForestRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/limited': typeof AuthenticatedLimitedRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/forest/calendar': typeof AuthenticatedForestCalendarRoute
  '/forest/shop': typeof AuthenticatedForestShopRoute
  '/forest/day/$day': typeof AuthenticatedForestDayDayRoute
  '/api/public/hooks/native-usage': typeof ApiPublicHooksNativeUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/forest': typeof AuthenticatedForestRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/limited': typeof AuthenticatedLimitedRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/forest/calendar': typeof AuthenticatedForestCalendarRoute
  '/_authenticated/forest/shop': typeof AuthenticatedForestShopRoute
  '/_authenticated/forest/day/$day': typeof AuthenticatedForestDayDayRoute
  '/api/public/hooks/native-usage': typeof ApiPublicHooksNativeUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/forest'
    | '/goals'
    | '/home'
    | '/limited'
    | '/permissions'
    | '/profile'
    | '/forest/calendar'
    | '/forest/shop'
    | '/forest/day/$day'
    | '/api/public/hooks/native-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/forest'
    | '/goals'
    | '/home'
    | '/limited'
    | '/permissions'
    | '/profile'
    | '/forest/calendar'
    | '/forest/shop'
    | '/forest/day/$day'
    | '/api/public/hooks/native-usage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/welcome'
    | '/_authenticated/forest'
    | '/_authenticated/goals'
    | '/_authenticated/home'
    | '/_authenticated/limited'
    | '/_authenticated/permissions'
    | '/_authenticated/profile'
    | '/_authenticated/forest/calendar'
    | '/_authenticated/forest/shop'
    | '/_authenticated/forest/day/$day'
    | '/api/public/hooks/native-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicHooksNativeUsageRoute: typeof ApiPublicHooksNativeUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/limited': {
      id: '/_authenticated/limited'
      path: '/limited'
      fullPath: '/limited'
      preLoaderRoute: typeof AuthenticatedLimitedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forest': {
      id: '/_authenticated/forest'
      path: '/forest'
      fullPath: '/forest'
      preLoaderRoute: typeof AuthenticatedForestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forest/shop': {
      id: '/_authenticated/forest/shop'
      path: '/shop'
      fullPath: '/forest/shop'
      preLoaderRoute: typeof AuthenticatedForestShopRouteImport
      parentRoute: typeof AuthenticatedForestRoute
    }
    '/_authenticated/forest/calendar': {
      id: '/_authenticated/forest/calendar'
      path: '/calendar'
      fullPath: '/forest/calendar'
      preLoaderRoute: typeof AuthenticatedForestCalendarRouteImport
      parentRoute: typeof AuthenticatedForestRoute
    }
    '/api/public/hooks/native-usage': {
      id: '/api/public/hooks/native-usage'
      path: '/api/public/hooks/native-usage'
      fullPath: '/api/public/hooks/native-usage'
      preLoaderRoute: typeof ApiPublicHooksNativeUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forest/day/$day': {
      id: '/_authenticated/forest/day/$day'
      path: '/day/$day'
      fullPath: '/forest/day/$day'
      preLoaderRoute: typeof AuthenticatedForestDayDayRouteImport
      parentRoute: typeof AuthenticatedForestRoute
    }
  }
}

interface AuthenticatedForestRouteChildren {
  AuthenticatedForestCalendarRoute: typeof AuthenticatedForestCalendarRoute
  AuthenticatedForestShopRoute: typeof AuthenticatedForestShopRoute
  AuthenticatedForestDayDayRoute: typeof AuthenticatedForestDayDayRoute
}

const AuthenticatedForestRouteChildren: AuthenticatedForestRouteChildren = {
  AuthenticatedForestCalendarRoute: AuthenticatedForestCalendarRoute,
  AuthenticatedForestShopRoute: AuthenticatedForestShopRoute,
  AuthenticatedForestDayDayRoute: AuthenticatedForestDayDayRoute,
}

const AuthenticatedForestRouteWithChildren =
  AuthenticatedForestRoute._addFileChildren(AuthenticatedForestRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedForestRoute: typeof AuthenticatedForestRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLimitedRoute: typeof AuthenticatedLimitedRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedForestRoute: AuthenticatedForestRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLimitedRoute: AuthenticatedLimitedRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicHooksNativeUsageRoute: ApiPublicHooksNativeUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
